# image_agent_pause_approval.py

# deps: pip install google-adk mcp python-dotenv
# Note: Package installs as 'google-adk' but imports as 'google.adk' (with dot)

# This demo focuses on the APPROVAL WORKFLOW.
# MCP Everything Server is integrated - requires Node.js/npx installed.

# Observação: mantemos o padrão FunctionTool + LlmAgent, sem @tool.



import asyncio

import uuid

import os

from typing import Dict, Any, List, Optional



# ---- ADK primitives (ajusta nomes se a tua versão divergir) ----

from google.adk.agents import LlmAgent

from google.adk.tools import FunctionTool

from google.adk.models import Gemini

from google.adk.apps import App, ResumabilityConfig



# ---- MCP (Everything Server via stdio) ----

from google.adk.tools.mcp_tool import McpToolset, StdioConnectionParams

from mcp import StdioServerParameters



# =========================

# API Key Setup

# =========================

# Try loading from config.py first

try:

    from config import GOOGLE_API_KEY

    os.environ["GOOGLE_API_KEY"] = GOOGLE_API_KEY

    print("✅ Setup and authentication complete (config.py).")


except ImportError:

    # Fall back to environment variable

    if os.getenv("GOOGLE_API_KEY"):

        print("✅ Using GOOGLE_API_KEY from environment variable.")

    else:

        print(

            "⚠️  Warning: GOOGLE_API_KEY not found!\n"

            "Please either:\n"

            "  1. Set GOOGLE_API_KEY in config.py, or\n"

            "  2. Set GOOGLE_API_KEY as an environment variable"

        )



# =========================

# MCP: Everything Server

# =========================

mcp_image_server = McpToolset(

    connection_params=StdioConnectionParams(

        server_params=StdioServerParameters(

            command="npx",

            args=["-y", "@modelcontextprotocol/server-everything"],

        ),

        timeout=30,

    )

)



# =========================

# Estado simples (p/ "pausa")

# =========================

# Guardamos pedidos pendentes para poder "retomar" depois da aprovação.

PENDING_ORDERS: Dict[str, Dict[str, Any]] = {}



# =========================

# Image generation helper

# =========================

async def _generate_images(n: int) -> List[str]:

    """

    Placeholder for image generation confirmation.

    Real images are generated by the AGENT calling MCP tools directly.

    This function just returns confirmation that images would be generated.

    """

    # O agente usa o MCP diretamente através das suas tools

    # Esta função apenas confirma o pedido

    return [f"✅ Image {i+1} of {n} - Ready for generation via MCP" for i in range(n)]



# =========================

# FunctionTools (sem @tool)

# =========================

async def place_image_order(prompt: str, num_images: int = 1, size: str = "1024x1024", model: Optional[str] = None) -> Dict[str, Any]:

    """

    - 1 imagem -> gera imediatamente (auto-aprovado).

    - >1 imagens -> devolve status 'pending' e approval_token (PAUSA até haver aprovação).

    """

    if num_images <= 1:

        imgs = await _generate_images(1)

        return {

            "status": "approved",

            "order_id": str(uuid.uuid4()),

            "count": 1,

            "images": imgs,

            "prompt": prompt,

            "size": size,

            "model": model or "",

        }



    # Pedido "bulk" -> PAUSA (pending) até aprovação

    approval_token = str(uuid.uuid4())

    PENDING_ORDERS[approval_token] = {

        "prompt": prompt,

        "num_images": num_images,

        "size": size,

        "model": model or "",

    }

    return {

        "status": "pending",

        "approval_token": approval_token,

        "message": f"Pedido de {num_images} imagens em aprovação. Usa approve_image_order para decidir.",

    }



async def approve_image_order(approval_token: str, approve: bool) -> Dict[str, Any]:

    """

    Aprova ou rejeita um pedido pendente (retoma o fluxo).

    """

    data = PENDING_ORDERS.pop(approval_token, None)

    if data is None:

        return {"status": "error", "message": "approval_token inválido ou já processado."}



    if not approve:

        return {

            "status": "rejected",

            "order_id": None,

            "reason": "Pedido rejeitado.",

            "prompt": data["prompt"],

            "num_images": data["num_images"],

        }



    imgs = await _generate_images(data["num_images"])

    return {

        "status": "approved",

        "order_id": str(uuid.uuid4()),

        "count": len(imgs),

        "images": imgs,

        "prompt": data["prompt"],

        "size": data["size"],

        "model": data["model"],

    }



# =========================

# Agente (no estilo do teu shipping_agent)

# =========================



image_agent = LlmAgent(

    name="image_generation_agent",

    model=Gemini(model="gemini-2.5-flash-lite"),

    instruction="""You are an image generation assistant with access to MCP tools.



When users request to generate images:

  1) Use the place_image_order tool with the prompt and number of images (num_images).

  2) If the tool returns status 'pending', inform the user that approval is required and provide the approval_token.

  3) When the user approves or rejects, call approve_image_order with the approval_token and the user's decision.

  4) After approval, you can optionally demonstrate the MCP integration by calling getTinyImage tool.

  5) Provide a clear summary including:

     - Final status (approved/rejected)

     - Order ID (if available)

     - Number of images requested

     - You have access to MCP tools like getTinyImage for actual image generation

  6) Keep responses concise but informative.

""",

    tools=[

        FunctionTool(func=place_image_order),

        FunctionTool(func=approve_image_order),

        mcp_image_server,  # MCP tools disponíveis para o agente

    ],

)



# =========================

# Wrap agent in App for resumability (KEY FOR LONG-RUNNING OPS!)

# =========================

image_app = App(

    name="image_generation_coordinator",

    root_agent=image_agent,

    resumability_config=ResumabilityConfig(is_resumable=True),

)



# =========================

# Demo rápido

# =========================

async def _demo():

    print("» Single (auto-aprova):")

    r1 = await place_image_order(prompt="tiny checkerboard", num_images=1)

    print(r1, "\n")



    print("» Bulk (PAUSA → pending):")

    r2 = await place_image_order(prompt="retro pixels", num_images=3)

    print(r2, "\n")



    if r2.get("status") == "pending":

        token = r2["approval_token"]

        print("» A aprovar o bulk…")

        r3 = await approve_image_order(token, approve=True)

        print(r3, "\n")



if __name__ == "__main__":

    asyncio.run(_demo())

